version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install pytest
  
  pre_build:
    commands:
      - pytest --junit-xml ./junit.xml
  
  build:
    commands:
      - sam build
      - sam package --s3-bucket wsi-abcd-30710-cfn-build --output-template-file outputtemplate.yml
  
  post_build:
    commands:
      - cat ./.aws-sam/build/template.yaml
      - cat outputtemplate.yml

reports:
  arn:aws:codebuild:ap-northeast-2:763745971502:report-group/wsi-report-group:
    files:
      - ./junit.xml

artifacts:
  files:
    - outputtemplate.yml
